### ISSUE TITLE
最低支持的 python 版本

### ISSUE THREAD

**Issue by czwen** [Hsiny/Shadowrocket-Config#6]
请问最低支持的 python 版本是多少？

**Comment by Hsiny** [comment]
python3可以，python2不支持。您有特别的需要？

**Comment by czwen** [comment]
客气了。
其实是我跑不起来。🙈


```
Traceback (most recent call last):
  File "srconfig.py", line 135, in <module>
    sConfig = SRConfig()
  File "srconfig.py", line 22, in __init__
    self.__downloadFile(self.__GFWListUrl,self.__DownloadFilePath+ self.__GFWListRuleFileName)
  File "srconfig.py", line 47, in __downloadFile
    response = urllib.request.urlopen(fileUrl)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 153, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 455, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 478, in _open
    'unknown_open', req)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 433, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/urllib/request.py", line 1244, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>
```

**Comment by Hsiny** [comment]
这个是你环境不支持ssl,你可以尝试下http://techglimpse.com/install-python-openssl-support-tutorial/ 
安装了open-ssl之后再重新装一下python

**Comment by czwen** [comment]
我更新到最新的python后可以了。谢谢
